# traefik.toml
logLevel = "DEBUG"
defaultEntryPoints = ["http"]
[entryPoints]
  [entryPoints.http]
    address = ":8080"

[frontends]
  [frontends.consul_ui]
    backend = "consul_ui"
    passHostHeader = true
  
[backends]
  [backends.consul_ui]
    [backends.consul_ui.servers.server1]
      url = "http://127.0.0.1:8500"

[web]
  address = ":8081"

[consul]
  endpoint = "127.0.0.1:8500"
  watch = true
  prefix = "traefik_2"
